stages:
    - build
    - deploy

variables:
    REGISTRY_HOST: localhost:5000
    TAG: $REGISTRY_HOST/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME:latest

build:
    stage: build
    image: docker
    rules:
        - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
    before_script:
        - docker info
    script:
        - docker build -t $TAG .
        - docker push $TAG

deploy:
    stage: deploy
    image: docker
    rules:
        - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
    before_script:
        - docker info
        - docker stop $CI_PROJECT_NAME || exit_code=$?
        - if [ $exit_code -ne 0 ]; then echo "Container not found, cannot stop"; else docker rm $CI_PROJECT_NAME; fi
    script:
        - docker run -d --restart always -p 8007:80 --name $CI_PROJECT_NAME $TAG
